# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish image

on:
  push:
    branches: ['main']
    tags: ['v*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Build and push local image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: react/Dockerfile
          target: prod
          push: true
          build-args: |
            BASE_PATH=/tomo_viewer/
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:local
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push ALS production image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: react/Dockerfile
          target: prod
          push: true
          build-args: |
            BASE_PATH=/bl832/tomo_viewer/
            FIXED_TILED_SERVER=tiled.als.lbl.gov
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:als-prod
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push ALS staging image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: react/Dockerfile
          target: prod
          push: true
          build-args: |
            BASE_PATH=/bl832/tomo_viewer/
            FIXED_TILED_SERVER=tiled-staging.als.lbl.gov
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:als-staging
          labels: ${{ steps.meta.outputs.labels }}
